### ISSUE TITLE
Failure on iOS

### ISSUE THREAD

**Issue by DarrellBrogdon** [manojdcoder/nativescript-canvas-interface-demo#2]
This is the output from trying to run on the iOS simulator.  iPhone XR running iOS 12.1.

`tns run ios
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Executing before-watch hook from /Users/dbrogdon/Documents/Development/NativeScriptCanvasInterfaceDemo/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
Executing before-prepare hook from /Users/dbrogdon/Documents/Development/NativeScriptCanvasInterfaceDemo/hooks/before-prepare/nativescript-dev-typescript.js
Preparing project...
node_modules/tns-core-modules/module.d.ts(43,9): error TS1131: Property or signature expected.
node_modules/tns-core-modules/module.d.ts(43,18): error TS1005: ';' expected.
node_modules/tns-core-modules/module.d.ts(44,24): error TS1005: ',' expected.
node_modules/tns-core-modules/module.d.ts(44,33): error TS1005: ';' expected.
node_modules/tns-core-modules/module.d.ts(45,26): error TS1005: ',' expected.
node_modules/tns-core-modules/module.d.ts(45,35): error TS1005: ';' expected.
node_modules/tns-core-modules/module.d.ts(46,34): error TS1005: ',' expected.
node_modules/tns-core-modules/module.d.ts(46,52): error TS1005: ',' expected.
node_modules/tns-core-modules/module.d.ts(46,58): error TS1005: ';' expected.
node_modules/tns-core-modules/module.d.ts(46,64): error TS1109: Expression expected.
node_modules/tns-core-modules/module.d.ts(47,31): error TS1005: ',' expected.
node_modules/tns-core-modules/module.d.ts(47,42): error TS1005: ';' expected.
node_modules/tns-core-modules/module.d.ts(48,17): error TS1109: Expression expected.
node_modules/tns-core-modules/module.d.ts(49,26): error TS1005: ',' expected.
node_modules/tns-core-modules/module.d.ts(49,40): error TS1109: Expression expected.
node_modules/tns-core-modules/module.d.ts(49,70): error TS1109: Expression expected.
node_modules/tns-core-modules/module.d.ts(49,76): error TS1005: ';' expected.
node_modules/tns-core-modules/module.d.ts(50,28): error TS1005: ',' expected.
node_modules/tns-core-modules/module.d.ts(50,42): error TS1109: Expression expected.
node_modules/tns-core-modules/module.d.ts(50,72): error TS1109: Expression expected.
node_modules/tns-core-modules/module.d.ts(50,78): error TS1005: ';' expected.
node_modules/tns-core-modules/module.d.ts(51,18): error TS1109: Expression expected.
node_modules/tns-core-modules/module.d.ts(52,21): error TS1109: Expression expected.
node_modules/tns-core-modules/module.d.ts(54,33): error TS1109: Expression expected.
node_modules/tns-core-modules/module.d.ts(55,37): error TS1109: Expression expected.
node_modules/tns-core-modules/module.d.ts(56,62): error TS1109: Expression expected.
node_modules/tns-core-modules/module.d.ts(57,21): error TS1109: Expression expected.
node_modules/tns-core-modules/module.d.ts(58,27): error TS1109: Expression expected.
node_modules/tns-core-modules/module.d.ts(60,1): error TS1128: Declaration or statement expected.
12:03:56 PM - Compilation complete. Watching for file changes.
Successfully prepared plugin nativescript-canvas-interface for ios.
Successfully prepared plugin tns-core-modules for ios.
Successfully prepared plugin nativescript-webview-interface for ios.
Successfully prepared plugin tns-core-modules-widgets for ios.
We have failed to check if we need to add a compatability LaunchScreen.xib due to: Error: ENOENT: no such file or directory, open '/Users/dbrogdon/Documents/Development/NativeScriptCanvasInterfaceDemo/app/App_Resources/iOS/Info.plist'
Unable to apply changes on device: 2F23F878-0C15-48A6-8FF8-F2000106A04E. Error is: ENOENT: no such file or directory, open '/Users/dbrogdon/Documents/Development/NativeScriptCanvasInterfaceDemo/platforms/ios/NativeScriptCanvasInterfaceDemo/NativeScriptCanvasInterfaceDemo-Info.plist'.`

**Comment by manojdcoder** [comment]
These are nothing related to actual code but just TypeScript rules. Which version of TypeScript you have in your machine? Try updating to latest.

**Comment by DarrellBrogdon** [comment]
I ran `npm install -g typescript@latest` which returned 
```
/usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
/usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
+ typescript@3.1.6
added 1 package from 1 contributor in 1.942s
```
 but that didn't fix anything. 

Which version should I be running?

**Comment by DarrellBrogdon** [comment]
On iOS, when I do `tns run ios` I get that output I pasted above but it never actually installs on the simulator.

**Comment by DarrellBrogdon** [comment]
For comparison; I'm able to run the demo app that NativeScript provides in their documentation without any problems.

**Comment by manojdcoder** [comment]
By default `tsconfig` ignores TypeScript compilation on `node_modules`. Not sure why it's being picked up in your case. This seems to be some issue with your build flow / configuration and not with the plugin.

**Comment by DarrellBrogdon** [comment]
Is it possible to run this example without TypeScript?  I really would prefer to use VanillaJS anyway.

**Comment by manojdcoder** [comment]
Yes, you can. Create new VanillaJS project and integrate the plugin. This sample relys on TypeScript.

**Comment by DarrellBrogdon** [comment]
Thank you and apologies for the delayed reply.  You have been very helpful!
